### ISSUE TITLE
Remove the face command because it uses a private api

### ISSUE THREAD

**Issue by rski** [nwops/puppet-debugger#52]
The faces API is private, so a non-face cli command would be a better option
https://docs.puppet.com/puppet/4.8/deprecated_api.html#puppet-faces-is-a-private-api

Plus, having a one word command would make the code for emacs' puppet mode simpler

**Comment by logicminds** [comment]
What do you propose?  `pdb` seemed to have been a bad choice sicne it conflicts with python debugger.  Also the puppet debugger command is not a face it is a application.  Similar but different.

The puppet debugger command is similar to puppet apply so I can't see it going away.

**Comment by logicminds** [comment]
I think puppet-debugger might be the most logical sense.  Thoughts?

**Comment by rski** [comment]
Yup, I'm down with that

**Comment by logicminds** [comment]
I wish I had known that naming a command to puppet-debugger would have automatically added a puppet app automatically.  Probably wasted a weeks worth of time trying to get the puppet application working.

**Comment by logicminds** [comment]
won't fix.
