### ISSUE TITLE
RVM causes the debugger command to not load 

### ISSUE THREAD

**Issue by sammcj** [nwops/puppet-debugger#62]
As per instructions:

```shell
~ gem install puppet puppet-debugger
Successfully installed puppet-5.5.6-universal-darwin
Successfully installed puppet-debugger-0.9.1
2 gems installed
```

```shell
~ puppet debugger
Error: Unknown Puppet subcommand 'debugger'
See 'puppet help' for help on available puppet subcommands
```

```ruby
~ gem list|grep puppet
puppet (5.5.6 universal-darwin)
puppet-debugger (0.9.1)
puppet-lint (2.3.6)
```

**Comment by logicminds** [comment]
thanks for reporting.  Not sure what changed.  In the meantime you can use the `pdb` command. Although if you have the python debugger this may conflict.

**Comment by sammcj** [comment]
Thanks @logicminds, Indeed it seems to work with the system ruby, does it perhaps have some hard coded paths in it's alias from pbd? (and yeah I use the python debugger of the same name so that clashed and threw me off at first!)

**Comment by logicminds** [comment]
No hard coded paths, but I think this is an issue with using relative path loading and RVM. I'll need to go back and change a few things later this week.

**Comment by shamil** [comment]
Have same issue with `RVM` on Ubuntu

**Comment by logicminds** [comment]
There is a bug in puppet core that is causing this issue.

The following code is the responsible code for not loading the puppet-debugger.
https://github.com/puppetlabs/puppet/blob/master/lib/puppet/util/rubygems.rb#L11

Essentially, RVM loads up bundler by default which causes puppet to ignore external gem directories (puppet-debugger) and many more gems with faces and applications.  This means that all puppet versions are affected.  

There is no way to fix this in the puppet-debugger code.  This is a puppet issue and an unfortunate side affect with bundler which RVM uses and loads by default.   

There are some workarounds:

1. Set the RUBYLIB path to always load the debugger code  (set in shell environment variable)
ie. `RUBYLIB=/home/worker/.rvm/gems/ruby-2.3.1/gems/puppet-debugger-0.10.1/lib puppet debugger`

2. Don't use RVM, use rbenv as this does not occur with [rbenv](https://github.com/rbenv/rbenv).
